services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./site:/var/www/blog.api
      - ./logs/nginx:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build: ./php-fpm
    links:
      - mysql
    volumes:
      - ./site:/var/www/blog.api

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: blog.api